function [text] = presentation_text();
text = {['MLE+ is a Matlab toolbox for co-simulation with the whole-building energy',...
    'simulator EnergyPlus. It is designed for engineers and researchers who are familiar ',...
    'with Matlab and Simulink and want to use these software tools in building energy simulation.'];...
    ' ';...
    'University of Pennsylvania';' ';...
    'Version 1.0'};
    
end